<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Vehiculo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehiculosSecretariaObrasPublicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $area = Area::where('prefijo_catalogacion', 'OP-')->first();

        $vehiculos = [
            [
                'catalogacion' => 'OP-001',
                'tipo' => 'CAMION',
                'marca' => 'VOLKSWAGEN',
                'modelo' => '17280',
                'patente' => 'AF-941-KX',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-002',
                'tipo' => 'CAMION',
                'marca' => 'MERCEDES BENZ',
                'modelo' => '16/20',
                'patente' => 'RYG754',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-003',
                'tipo' => 'CAMION',
                'marca' => 'IVECO',
                'modelo' => 'ATTACK',
                'patente' => 'NIS-698',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-004',
                'tipo' => 'CAMION',
                'marca' => 'IVECO',
                'modelo' => 'ATTACK',
                'patente' => 'NIJ-647',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-005',
                'tipo' => 'CAMION',
                'marca' => 'FORD',
                'modelo' => 'CARGO',
                'patente' => 'GNA-367',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-006',
                'tipo' => 'CAMION',
                'marca' => 'FORD',
                'modelo' => 'CARGO',
                'patente' => 'GON-352',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-007',
                'tipo' => 'CAMION',
                'marca' => 'IVECO',
                'modelo' => 'CURSOR',
                'patente' => 'AC-869-XQ',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-008',
                'tipo' => 'CAMION',
                'marca' => 'IVECO',
                'modelo' => 'ATTACK',
                'patente' => 'AA-976-QY',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-009',
                'tipo' => 'CAMIONETA',
                'marca' => 'FORD',
                'modelo' => 'RANGER',
                'patente' => 'JKA 205',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-010',
                'tipo' => 'COLECTIVO',
                'marca' => 'MERCEDES BENZ',
                'modelo' => '—',
                'patente' => 'WIE744',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-011',
                'tipo' => 'AMBULANCIA',
                'marca' => 'MERCEDES BENZ',
                'modelo' => 'SPRINTER',
                'patente' => 'GYB 305',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-012',
                'tipo' => 'MINI BUS',
                'marca' => 'MERCEDES BENZ',
                'modelo' => 'SPRINTER',
                'patente' => 'FO 0995',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-013',
                'tipo' => 'MINI CARGADORA',
                'marca' => 'BOB CAT',
                'modelo' => '—',
                'patente' => 'N/A0',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-014',
                'tipo' => 'MOTO NIVELADORA',
                'marca' => 'NEW HOLLAND',
                'modelo' => '—',
                'patente' => 'N/A1',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-015',
                'tipo' => 'MOTO NIVELADORA',
                'marca' => 'PAUNY',
                'modelo' => '—',
                'patente' => 'N/A2',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-016',
                'tipo' => 'RETRO EXCAVADORA',
                'marca' => 'JCB',
                'modelo' => '—',
                'patente' => 'EAT97',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-017',
                'tipo' => 'RETRO EXCAVADORA',
                'marca' => 'RETRO',
                'modelo' => '96',
                'patente' => 'A65',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-018',
                'tipo' => 'TRACTOR',
                'marca' => 'DEUTZ',
                'modelo' => '6008',
                'patente' => 'N/A3',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-019',
                'tipo' => 'TRACTOR PRODUCCION',
                'marca' => 'MASSEY FERGUSON',
                'modelo' => '2625',
                'patente' => 'N/A4',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-020',
                'tipo' => 'TRACTOR',
                'marca' => 'MASSEY FERGUSON',
                'modelo' => '2625',
                'patente' => 'N/A5',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-021',
                'tipo' => 'TRACTOR',
                'marca' => 'DEUTZ',
                'modelo' => '65',
                'patente' => 'N/A6',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-022',
                'tipo' => 'TRACTOR',
                'marca' => 'MASSEY FERGUSON',
                'modelo' => '265',
                'patente' => 'N/A7',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-023',
                'tipo' => 'TRACTOR',
                'marca' => 'MASSEY FERGUSON',
                'modelo' => '165',
                'patente' => 'FSK 295',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-024',
                'tipo' => 'UTILITARIO',
                'marca' => 'RENAULT',
                'modelo' => 'KANGOO',
                'patente' => 'N/A8',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-025',
                'tipo' => 'VIBRO COMPACTADOR',
                'marca' => 'VIBRO PLANE',
                'modelo' => '—',
                'patente' => 'N/A9',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
            [
                'catalogacion' => 'OP-026',
                'tipo' => 'CAMIONETA',
                'marca' => 'VOLKSWAGEN',
                'modelo' => 'SAVEIRO',
                'patente' => 'N/A10',
                'imagen' => null,
                'anio' => null,
                'color' => null,
                'motor' => null,
                'chasis' => null,
                'tipo_combustible_id' => 1,
            ],
        ];

        foreach ($vehiculos as $vh) {
            Vehiculo::updateOrCreate([
                'catalogacion' => $vh['catalogacion'],
                'tipo'         => $vh['tipo'],
                'marca'        => $vh['marca'],
                'modelo'       => $vh['modelo'],
                'patente'      => $vh['patente'],
                'imagen'      => $vh['imagen'],
                'anio'        => $vh['anio'],
                'color'       => $vh['color'],
                'motor'       => $vh['motor'],
                'chasis'      => $vh['chasis'],
                'area_id'      => $area->id,
                'tipo_combustible_id' => $vh['tipo_combustible_id'],
                'estado'       => true,
            ]);
        }
    }
}
